### ISSUE TITLE
Load user relays

### ISSUE THREAD

**Issue by natoe33** [vivganes/zapddit#20]
Currently, Zapddit doesn’t retrieve the subscribed relays for the logged in user. Need to retrieve the kind 3 event and add the relays to the relay pool. 

Current default relays:
`'wss://nos.lol',
  'wss://relay.nostr.band',
  'wss://relay.f7z.io',
  'wss://relay.damus.io',
  'wss://nostr.mom',
  'wss://no.str.cr'`

**Comment by natoe33** [comment]
@vivganes You can assign this to me since I’m working on it already.

**Comment by ralyodio** [comment]
nice,... looking forward to it.

**Comment by vivganes** [comment]
fixed by #31
