### ISSUE TITLE
stale feed

### ISSUE THREAD

**Issue by ralyodio** [vivganes/zapddit#34]
If I go here: https://tags.break-19.com/feed

last post was 18 hours ago, but if i click on individual tags I get recent results.

Did I misconfigure something?

**Comment by vivganes** [comment]
Thanks for reporting this issue. @trycatchkamal  and I have been seeing that the posts are not sorted in reverse chronological order.  This is more visible in the "My feed" section than the individual hashtags.

Your configuration is correct. Just that the posts are not sorted in reverse time order.  You can observe this bug in individual hashtags feed too i guess (though less manifested).

We will investigate and push a fix sooner than later.

Thanks again 🙏

**Comment by vivganes** [comment]
https://github.com/vivganes/zapddit/pull/35 fixes this
